[package]
name = "cppship"
version = "0.1.0"
edition = 2023
authors = []

[dependencies]
zlib = "1.2.11"
structopt = "0.1.3"
boost = "1.81.0"
libgit2 = "1.5.0"
toml11 = "3.7.1"
fmt = "9.1.0"
range-v3 = "0.12.0"
bshoshany-thread-pool = "3.3.0"
ms-gsl = "4.0.0"
ninja = "1.11.1"